### ISSUE TITLE
Upgrade to Cats 0.9.0

### ISSUE THREAD

**Issue by durban** [durban/seals#41]
Blocked by:

- [x] circe 0.7.0 (circe/circe/pull/548)
- [x] scodec-cats (scodec/scodec-cats/pull/5)
- [x] fs2-cats (functional-streams-for-scala/fs2-cats/pull/17)

After these:

- [x] actually upgade to Cats 0.9.0

**Comment by travisbrown** [comment]
Circe's out! By the way, it'd be great to have this project linked from the related projects list in the circe README. 😄

**Comment by durban** [comment]
Thanks! Ok, I'll send a pull request.
