### ISSUE TITLE
Can we mention seals in cats' README?

### ISSUE THREAD

**Issue by kailuowang** [durban/seals#62]
in the list of cats ecosystem projects.

**Comment by durban** [comment]
If this means no more than "this stuff is intended to work reasonably well with Cats", then sure. If you can confirm this, I'll send a PR. Thanks!

**Comment by kailuowang** [comment]
It also means that you agree to start pay me a $199.99/mo subscription fee. Is that okay? 😄
What you said is exactly what it means. Thanks!

**Comment by durban** [comment]
Addressed by https://github.com/typelevel/cats/pull/1817. Thanks!
