### ISSUE TITLE
Is Seals maintained?

### ISSUE THREAD

**Issue by BenHutchisonSeek** [durban/seals#70]
Hi Daniel,

I like the intent behind seals, Ive hit the problem it tackles in my work. Noticed that seals stopped at Feb 18, 20 months ago, so wondering wether this should be considered an actively maintained project or an experiment?

**Comment by durban** [comment]
Hi,

It's definitely an experiment. That being said, I plan to continue the experiment when I get around to it.

Necessary maintenance work I can immediately see right now is to:

- upgrade dependencies to recent versions;
- move to another groupId/package name (as I no longer own the domain it currently uses).

If there is interest, I can look into these. (Also, pull requests are welcome :-)

Please let me know if this answers your questions.
